---

- name: create overlay directory
  file:
    path: '{{ item }}'
    state: directory
    owner: root
    group: root
    mode: 0755
  become: yes
  loop:
    - /etc/portage/repos.conf
    - /var/db/repos/expeditioneer

- name: install git
  package:
    name:
      - dev-vcs/git
  become: yes

- name: add required expeditioneer overlay
  template:
    src: expeditioneer-overlay.j2
    dest: /etc/portage/repos.conf/expeditioneer.conf
    owner: root
    group: root
    mode: 0644
  become: yes
  register: expeditioneer_overlay

- name: sync all portage overlays
  command: eix-sync
  become: yes
  when: expeditioneer_overlay.changed
